Fleshing out ge-svn-import

diff --git a/ge-svn-import b/ge-svn-import
--- a/ge-svn-import
+++ b/ge-svn-import
@@ -4,7 +4,7 @@ current_dir=`pwd`
 git_svn_init_args=""
 git_svn_fetch_args=""
 interactive_mode=0
-log_file="./svn_import.log"
+log_file="./svn_import_`date '+%Y-%m-%d_%H.%M.%S'`.log"
 svn_authors_files=""
 svn_destination_dir=""
 svn_repo_url=""
@@ -13,12 +13,6 @@ svn_username=""
 
 function ge_svn_import() {
 	touch $log_file
-	#echo "Importing svn repo from URL $svn_repo_url"
-	#echo "to local directory $svn_destination_dir"
-	#echo "with username $svn_username. Authors are coming from"
-	#echo "$svn_authors_file, and messages logged to"
-	#echo "$log_file"
-
 	(ge_svn_import_steps $@) | tee $log_file
 }
 
@@ -32,32 +26,13 @@ function ge_svn_import_steps() {
 
 	if [ -z "$svn_authors_file" ]; then
 		echo "WARN: No SVN authors file was found. Your new Git history will be incomplete."
-	elif [ ! -z "$svn_authors_file" ] && [ ! -f $svn_authors_file ]; then
+	elif [ ! -f "$svn_authors_file" ]; then
 		echo "FATAL: The SVN authors file ($svn_authors_file) does not exist or is not readable."
 		exit 1
 	else
 		echo "Using $svn_authors_file to import SVN history."
-		git_svn_fetch_args="$git_svn_fetch_args --authors-file=$svn_authors_file"
-		git_svn_init_args="$git_svn_init_args --authors-file=$svn_authors_file"
 	fi
 	
-	if [ -d $svn_destination_dir ]; then
-		echo "WARN: Destination directory already exists. Deleting the destination directory..."
-		echo "rm -vrf $svn_destination_dir"
-		rm -vrf $svn_destination_dir
-	fi
-	
-	echo "Creating destination directory $svn_destination_dir..."
-	echo "mkdir -vp $svn_destination_dir"
-	mkdir -vp $svn_destination_dir
-
-	if [ ! -d $svn_destination_dir ]; then
-		echo "FATAL: Failed to create $svn_destination_dir."
-		exit 1
-	else
-		echo "Destination directory created at $svn_destination_dir"
-	fi
-
 	echo "Listing contents of SVN repository URL..."
 	svn ls $svn_repo_url
 
@@ -66,6 +41,23 @@ function ge_svn_import_steps() {
 		exit 1
 	else
 		echo "The SVN repository URL $svn_repo_url exists."
+	fi
+	
+	if [ -d $svn_destination_dir ]; then
+		echo "WARN: Destination directory already exists. Deleting the destination directory..."
+		echo "rm -rf $svn_destination_dir"
+		rm -rf $svn_destination_dir
+	fi
+	
+	echo "Creating destination directory $svn_destination_dir..."
+	echo "mkdir -vp $svn_destination_dir"
+	mkdir -vp $svn_destination_dir
+	
+	if [ ! -d $svn_destination_dir ]; then
+		echo "FATAL: Failed to create $svn_destination_dir."
+		exit 1
+	else
+		echo "Destination directory created at $svn_destination_dir"
 	fi
 
 	echo "Initializing the Git-SVN repository..."
@@ -78,8 +70,8 @@ function ge_svn_import_steps() {
 	echo "git svn fetch --authors-file=$svn_authors_file -r $svn_start_revision:HEAD"
 	git svn fetch --authors-file=$svn_authors_file -r $svn_start_revision:HEAD
 	echo "Finished fetching commits."
-
-	echo "Finished."
+	ge_svn_convert_tags_to_branches	
+	echo "Finished importing into Git."
 }
 
 function ge_svn_import_interactive() {
@@ -104,8 +96,8 @@ function ge_svn_import_read_username() {
 }
 
 function ge_svn_import_read_authors_file() {
-	echo -n "SVN authors file: "
-	read -e svn_authors_file
+	read -e -p "SVN authors file: " svn_authors_file
+	eval svn_authors_file=$svn_authors_file
 	echo "# SVN authors file located at $svn_authors_file"
 }
 
@@ -121,37 +113,69 @@ function ge_svn_import_read_revision() {
 }
 
 function ge_svn_import_read_destination_dir() {
-	echo -n "Destination directory: "
-	read -e svn_destination_dir
+	read -e -p "Destination directory: " svn_destination_dir
+	eval svn_destination_dir=$svn_destination_dir
 	echo "# Creating Git repo in $svn_destination_dir"
 }
 
-while [ ! -z "$1" ]; do
-	case $1 in
-		'--interactive')
-			shift
-			interactive_mode=1
-			;;
-		'--svn-authors-file')
-			shift
-			svn_authors_file=$1
-			shift
-			;;
-		'--revision')
-			shift
-			svn_start_revision=$1
-			shift
-			;;
-		'--username')
-			shift
-			svn_username=$1
-			shift
-			;;
-		*)
-			break
-			;;
-	esac
-done
+function ge_svn_debug_convert_tags_to_branches() {
+	ge_svn_convert_tags_to_branches
+}
+
+function ge_svn_debug_git_branch() {
+	echo "  origin/foo"
+	echo "  origin/master"
+	echo "  tags/1"
+	echo "  tags/2"
+	echo "  tags/abc"
+}
+
+function ge_svn_convert_tags_to_branches() {
+	tag_branches=`git branch -r | grep -E '^  tags'`
+	echo "Convert SVN tags to Git tags. SVN tags get imported to Git as Git branches. Transform the following Git branches into Git tags:"
+	echo "$tag_branches"
+	
+	for branch in $tag_branches; do
+		tag=`echo $branch | sed -E 's/tags\/([-_a-zA-Z0-9]+)/\1/'`
+		echo "Convert Git-SVN branch $branch to Git tag $tag"
+		echo "  git tag $tag $branch"
+		git tag $tag $branch
+		echo "  git branch -r -d $branch"
+		git branch -r -d $branch
+	done
+	
+	echo "git tag"
+	git tag
+
+	echo "Finished converting SVN tags to Git tags."
+}
+
+if [ -z "$1" ]; then
+	interactive_mode=1
+else
+	while [ ! -z "$1" ]; do
+		case $1 in
+			'--svn-authors-file')
+				shift
+				svn_authors_file=$1
+				shift
+				;;
+			'--revision')
+				shift
+				svn_start_revision=$1
+				shift
+				;;
+			'--username')
+				shift
+				svn_username=$1
+				shift
+				;;
+			*)
+				break
+				;;
+		esac
+	done
+fi
 
 if [ $interactive_mode -eq 1 ]; then
 	echo "Entering interactive mode..."
